#!/bin/bash
# Autor: Telegram
TOKEN="SEU TOKEN"
 
USER=-ID do GRUPO
SUBJECT=$2
MESSAGE="A API está funcionando ✅"
PROBLEM=$4
NL="
"
curl --silent -X POST --data-urlencode "chat_id=${USER}" --data-urlencode "text=${SUBJECT}${NL}${NL}${MESSAGE}${NL}${PROBLEM}" "https://api.telegram.org/bot${TOKEN}/sendMessage?disable_web_page_preview=true&parse_mode=html" | grep -q '"ok":true'
 
exit 0
